name: Code Duplication Check

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  duplication:
    name: Code Duplication Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Copie code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup environnement java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Analyse du code
      - name: Run PMD CPD
        run: mvn pmd:cpd-check
