name: Java Lint (Checkstyle)

on:
  push:
    branches: [ "main", "master", "release/*" ]
  pull_request:
    branches: [ "main", "master", "release/*" ]

jobs:
  lint:
    name: Java Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Copie code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup environnement java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Analyse du code
      - name: Run Checkstyle
        run: mvn -Pci checkstyle:check
