name: Release Build

permissions:
  contents: write

# Déclenchement uniquement sur les tags de release
on:
  push:
    tags:
      - 'v*'  # ex: v1.0.0
  workflow_dispatch: # permet de déclencher manuellement

jobs:
  build:
    name: Build and Test (Release)
    runs-on: ubuntu-latest

    steps:
      # Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # nécessaire pour récupérer les tags

      # Installation du JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      # Vérifier que le tag est sur main
      # - name: Verify tag is on main
      #   run: |
      #     git fetch origin main
      #     git branch --contains $GITHUB_SHA | grep -q "main"

      # Build + tests Maven
      - name: Build and run tests
        run: mvn --batch-mode clean verify

      # Vérifier l'existance de les artfacts
      - name: List target directory
        run: ls -lh target

      # Publier les artifacts pour release
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 2048-jar-${{ github.ref_name }}
          path: target/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: 2048-jar-${{ github.ref_name }}
          path: ./target

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: target/*.jar

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/*.jar
          asset_name: 2048-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive